In [1]:
import pandas as pd

In [2]:
customers_data = pd.read_csv("Customers.csv")
products_data = pd.read_csv("Products.csv")
sales_2024 = pd.read_csv("Sales_2024.csv")
sales_2025 = pd.read_csv("Sales_2025.csv")
print("All csv files are saved in the given variables.")

All csv files are saved in the given variables.

In [3]:
customers_data.head(5)

,CustomerID,CustomerName,CustomerType,City,Country,JoinedYear,VIPLevel
0,C1,DJ Arman Blaze,DJ,Mumbai,India,2022,Platinum
1,C2,Sonic Wave Studios,Studio Engineer,Delhi,India,2021,Gold
2,C3,Neon Pulse,Producer,Bangalore,India,2023,Gold
3,C4,Aural Mastering Lab,Studio Engineer,London,UK,2020,Platinum
4,C5,DJ TitanBeats,DJ,Dubai,UAE,2022,Gold

In [4]:
customers_data.shape

(330, 7)

In [5]:
products_data.head(5)

,ProductID,ProductName,Category,LaunchYear,BasePriceINR,DriverType,ImpedanceOhm
0,P1,Titan X Elite,Flagship,2023,120000,Tribrid,16
1,P2,Aurora MKII,Flagship,2023,150000,Hybrid,18
2,P3,Phantom Ultra,Flagship,2024,180000,Tribrid,12
3,P4,Sonic Emperor Pro,Flagship,2024,200000,Quadbrid,10
4,P5,Valkyrie Xtreme,Flagship,2023,170000,Hybrid,14

In [6]:
products_data.shape

(15, 7)

In [7]:
sales_2024.head(5)

     OrderID   OrderDate ProductID CustomerID  Quantity  UnitPriceINR
0  S2024_001  22-06-2024        P3        C12         1        180000
1  S2024_002  26-11-2024        P1        C45         1        120000
2  S2024_003  22-04-2024        P7       C102         1        160000
3  S2024_004  15-05-2024        P4        C88         1        200000
4  S2024_005  04-08-2024        P9       C150         1        190000

In [8]:
sales_2024.shape

(451, 6)

In [9]:
sales_2025.head(5)

     OrderID   OrderDate ProductID CustomerID  Quantity  UnitPriceINR
0  S2025_001  23-08-2025        P3       C206         1        180000
1  S2025_002  26-11-2025        P1       C183         1        120000
2  S2025_003  03-05-2025        P7       C291         1        160000
3  S2025_004  29-05-2025        P4       C207         1        200000
4  S2025_005  23-12-2025        P9       C204         1        190000

In [10]:
sales_2025.shape

(646, 6)

🥊 Round 1 – Data Analysis Tasks
1) I want to know how many total orders were placed in 2024 and 2025 combined, Return one number only.
2) Show me top 5 customers who purchased the most quantity of products across both years combined.
- Output should contain:
- CustomerID
- TotalQuantity

3) I want to understand which product generated the highest revenue across both years.
- Revenue = Quantity * UnitPriceINR

In [11]:
customers_data['VIPLevel'] = customers_data['VIPLevel'].str.replace('0', 'Bronze')

In [12]:
customers_data.VIPLevel.value_counts()

VIPLevel
Bronze      300
Gold         15
Platinum      9
Silver        6
Name: count, dtype: int64

In [13]:
# Q.2
sales_data = pd.concat([sales_2024, sales_2025])

In [14]:
sales_n_customers = sales_data.merge(customers_data, on = "CustomerID").merge(products_data, on = "ProductID")

sales_n_customers.groupby('CustomerID')['Quantity'].sum().sort_values(ascending=False).head(5)

CustomerID
C330    11
C226    10
C202    10
C266     9
C232     9
Name: Quantity, dtype: int64

In [15]:
products_data.head(2)

,ProductID,ProductName,Category,LaunchYear,BasePriceINR,DriverType,ImpedanceOhm
0,P1,Titan X Elite,Flagship,2023,120000,Tribrid,16
1,P2,Aurora MKII,Flagship,2023,150000,Hybrid,18

In [16]:
sales_data.merge(products_data, on="ProductID").groupby("ProductName")[["Quantity", "UnitPriceINR"]].sum().sort_values(by="UnitPriceINR", ascending=False)

                   Quantity  UnitPriceINR
ProductName
Reference King           89      20400000
Titanium Pro X           90      19140000
Zeus Audio Pro           88      18500000
Obsidian X               87      17640000
Studio Monarch           96      15050000
Phantom Ultra            81      14220000
Crimson Audio X          66      13570000
Sonic Emperor Pro        76      13200000
Valkyrie Xtreme          75      11730000
Royal Bassline           64      11400000
Galaxy Monitor           84      10850000
Harmonic Beast           80      10360000
Aurora MKII              84      10350000
Nebula Prime             72      10240000
Titan X Elite            79       8520000

In [17]:
sales_data.head(2)

     OrderID   OrderDate ProductID CustomerID  Quantity  UnitPriceINR
0  S2024_001  22-06-2024        P3        C12         1        180000
1  S2024_002  26-11-2024        P1        C45         1        120000

In [18]:
sales_data['OrderDate'] = pd.to_datetime(sales_data['OrderDate'])

C:\Users\Kartik\AppData\Local\Temp\ipykernel_19184\3540728264.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  sales_data['OrderDate'] = pd.to_datetime(sales_data['OrderDate'])

In [19]:
sales_data['Year'] = sales_data['OrderDate'].dt.year

In [20]:
sales_data['OrderID'].count()

len(sales_data)

1097

In [21]:
sales_data

       OrderID  OrderDate ProductID CustomerID  Quantity  UnitPriceINR  Year
0    S2024_001 2024-06-22        P3        C12         1        180000  2024
1    S2024_002 2024-11-26        P1        C45         1        120000  2024
2    S2024_003 2024-04-22        P7       C102         1        160000  2024
3    S2024_004 2024-05-15        P4        C88         1        200000  2024
4    S2024_005 2024-08-04        P9       C150         1        190000  2024
..         ...        ...       ...        ...       ...           ...   ...
641  S2025_642 2025-02-22       P15       C282         1        240000  2025
642  S2025_643 2025-04-02       P10       C344         1        175000  2025
643  S2025_644 2025-04-17       P13       C150         1        140000  2025
644  S2025_645 2025-05-04        P2       C240         1        150000  2025
645  S2025_646 2025-12-07        P4       C239         1        200000  2025

[1097 rows x 7 columns]

In [22]:
sales_data

       OrderID  OrderDate ProductID CustomerID  Quantity  UnitPriceINR  Year
0    S2024_001 2024-06-22        P3        C12         1        180000  2024
1    S2024_002 2024-11-26        P1        C45         1        120000  2024
2    S2024_003 2024-04-22        P7       C102         1        160000  2024
3    S2024_004 2024-05-15        P4        C88         1        200000  2024
4    S2024_005 2024-08-04        P9       C150         1        190000  2024
..         ...        ...       ...        ...       ...           ...   ...
641  S2025_642 2025-02-22       P15       C282         1        240000  2025
642  S2025_643 2025-04-02       P10       C344         1        175000  2025
643  S2025_644 2025-04-17       P13       C150         1        140000  2025
644  S2025_645 2025-05-04        P2       C240         1        150000  2025
645  S2025_646 2025-12-07        P4       C239         1        200000  2025

[1097 rows x 7 columns]

In [23]:
sales_data.assign(
    Revenue = sales_data['Quantity'] * sales_data['UnitPriceINR']
).groupby("ProductID")['Revenue'].sum().sort_values(ascending=False)

ProductID
P11    22000000
P15    21360000
P12    19800000
P6     18270000
P10    16800000
P4     15200000
P8     15180000
P3     14580000
P14    13020000
P5     12750000
P2     12600000
P9     12160000
P7     11520000
P13    11200000
P1      9480000
Name: Revenue, dtype: int64

🥊 Round 2 – New Tasks (No Hints)
1) Show me total revenue generated in 2024 and 2025 separately. OUTPUT: Year | TotalRevenue

2) Find top 3 cities that purchased the highest number of products. OUTPUT: City | TotalQuantity

3) I want to know which DriverType generated the highest revenue. OUTPUT: DriverType | TotalRevenue

In [24]:
# Q.1
sales_data.assign(
    Revenue = sales_data["Quantity"] * sales_data["UnitPriceINR"]
).groupby("Year")["Revenue"].sum()

Year
2024     92630000
2025    133290000
Name: Revenue, dtype: int64

In [25]:
# Q.2
sales_data.merge(products_data, on="ProductID").merge(customers_data, on="CustomerID").groupby("City")['Quantity'].sum().sort_values(ascending=False).head(3)

City
Delhi          83
Los Angeles    81
Berlin         81
Name: Quantity, dtype: int64

In [26]:
#Q. 3
mereged_data = sales_data.merge(products_data, on="ProductID")
mereged_data.assign(
    Revenue = mereged_data["Quantity"] * mereged_data['UnitPriceINR']
).groupby("DriverType")["Revenue"].sum().sort_values(ascending=False).head(1)

DriverType
Quadbrid    73740000
Name: Revenue, dtype: int64

🥊 Round 3 – New Boss Requests

1) I want to know which 5 products generated the highest total revenue across both years.  ProductName | TotalRevenue

2) Find how many customers belong to each VIP level.  VIPLevel | CustomerCount

3) I want to know which customer spent the most money across both years. OUTPUT: CustomerName | TotalSpent

In [27]:
# Q.1
mereged_data.assign(
    Revenue = mereged_data["Quantity"] * mereged_data['UnitPriceINR']
).groupby("ProductName")['Revenue'].sum().sort_values(ascending=False).head(5)

ProductName
Zeus Audio Pro    22000000
Reference King    21360000
Titanium Pro X    19800000
Obsidian X        18270000
Studio Monarch    16800000
Name: Revenue, dtype: int64

In [28]:
# Q.2
customers_data['VIPLevel'].value_counts()

VIPLevel
Bronze      300
Gold         15
Platinum      9
Silver        6
Name: count, dtype: int64

In [29]:
# Q.3
merge_cs = sales_data.merge(customers_data, on="CustomerID")
merge_cs.assign(
    Revenue = merge_cs["Quantity"] * merge_cs['UnitPriceINR']
).groupby("CustomerName")["Revenue"].sum().sort_values(ascending=False).head(1)

CustomerName
DJ Apex Kabir    2035000
Name: Revenue, dtype: int64

🥊 Round 4 — Boss Needs New Analysis 
1) Find top 5 countries that generated the highest revenue.   Country | TotalRevenue
2) I want to know which year sold the highest number of products (by quantity).   Year | TotalQuantity
3) Find the most popular product category based on total quantity sold.  Category | TotalQuantity

In [30]:
#1
cus_and_sales_merge = sales_data.merge(customers_data, on="CustomerID")
cus_and_sales_merge.assign(
    Revenue = cus_and_sales_merge["Quantity"] * cus_and_sales_merge["UnitPriceINR"]
).groupby("Country")["Revenue"].sum().sort_values(ascending=False).head(5)

Country
India            37680000
United States    29705000
Germany          15480000
Japan            14855000
Canada           14240000
Name: Revenue, dtype: int64

In [31]:
#2
sales_data.groupby("Year")["Quantity"].sum().sort_values(ascending=False).head(1)

Year
2025    714
Name: Quantity, dtype: int64

In [32]:
#3
sales_data.merge(products_data, on="ProductID").groupby("Category")["Quantity"].sum().sort_values(ascending=False).head(1)

Category
Flagship    1211
Name: Quantity, dtype: int64

🥊 Round 5 – Mixed Pandas Practice
1) Show all sales where Quantity > 3.
- OrderID
- ProductID
- Quantity
- UnitPriceINR

2) Create a new column called: BigOrder
- Quantity >= 3 → "Yes"
- otherwise → "No"

3) Find the average price of products in each Category.
- Category | AvgPrice          Sorted highest first.

4) Show all Platinum customers from India.
- CustomerName
- City
- Country
- VIPLevel

5) Harder – Order Value: Create a column: OrderValue = Quantity * UnitPriceINR Then find top 5 highest single orders.
- OrderID
- CustomerID
- OrderValue

In [33]:
#1
sales_data[sales_data['Quantity'] > 3] [["OrderID","ProductID","Quantity","UnitPriceINR"]]

       OrderID ProductID  Quantity  UnitPriceINR
111  S2024_112        P8         4        230000
171  S2024_172       P14         6        155000
327  S2024_328        P1         4        120000
337  S2024_338       P11         4        250000
357  S2024_358        P5         4        170000
446  S2024_447       P13         4        140000
111  S2025_112        P8         4        230000
171  S2025_172       P14         6        155000
327  S2025_328        P1         4        120000
337  S2025_338       P11         4        250000
357  S2025_358        P5         4        170000
446  S2025_447       P13         4        140000
534  S2025_535        P6         4        210000
640  S2025_641       P10         9        175000

In [34]:
import numpy as np

sales_data["BigOrder"] = np.where(sales_data['Quantity'] >= 3, "Yes", "No")

In [35]:
sales_data[sales_data['BigOrder'] == "Yes"].head(2)

,OrderID,OrderDate,ProductID,CustomerID,Quantity,UnitPriceINR,Year,BigOrder
91,S2024_092,2024-02-28,P4,C19,3,200000,2024,Yes
111,S2024_112,2024-02-25,P8,C163,4,230000,2024,Yes

In [36]:
#3
products_data.groupby("Category")['BasePriceINR'].mean().sort_values(ascending=False)

Category
Flagship    186000.0
Name: BasePriceINR, dtype: float64

In [37]:
#4
customers_data[customers_data['VIPLevel'] == "Platinum"] [["CustomerName","City","Country","VIPLevel"]]

              CustomerName         City  Country  VIPLevel
0           DJ Arman Blaze       Mumbai    India  Platinum
3      Aural Mastering Lab       London       UK  Platinum
5         Studio Harmonics  Los Angeles      USA  Platinum
8       Platinum Sound Lab       Berlin  Germany  Platinum
11     Crystal Mix Studios       London       UK  Platinum
15        Velvet Audio Lab  Los Angeles      USA  Platinum
21  Harmonic Fusion Studio     New York      USA  Platinum
24    Golden Frequency Lab  Los Angeles      USA  Platinum
27     SonicAlchemy Studio       London       UK  Platinum

In [38]:
#5
sales_data.assign(
    OrderValue = sales_data['Quantity'] * sales_data["UnitPriceINR"]
).sort_values(by="OrderValue", ascending=False) [["OrderID","CustomerID","OrderValue"]]

       OrderID CustomerID  OrderValue
640  S2025_641       C385     1575000
337  S2025_338       C384     1000000
337  S2024_338       C267     1000000
171  S2025_172       C332      930000
171  S2024_172        C44      930000
..         ...        ...         ...
79   S2024_080       C269      120000
325  S2025_326       C319      120000
321  S2025_322       C394      120000
206  S2024_207        C83      120000
184  S2024_185       C210      120000

[1097 rows x 3 columns]

🥊 Round 6 – Real Analyst Style Tasks
1) New Column – Price Tier
- Price >= 200000 → "Ultra Premium"
- 150000–199999 → "Premium"
- Below 150000 → "Standard"

2) Find top 5 customers by total spending.  CustomerName | TotalSpent

3) Find top 3 most frequently ordered products.  ProductName | OrderCount

4) Find total revenue generated in each city.  City | TotalRevenue   Highest first

5) Find customers who placed more than 3 orders.  CustomerID | OrderCount

In [39]:
#1
sales_data["PriceTier"] = np.where(sales_data["UnitPriceINR"] >= 200000, "Ultra Premium",
                                   np.where(sales_data["UnitPriceINR"].between(150000, 199999), "Premium", "Standard"))

In [40]:
sales_data.PriceTier.value_counts()

PriceTier
Premium          497
Ultra Premium    455
Standard         145
Name: count, dtype: int64

In [41]:
#2
sales_data.merge(customers_data, on="CustomerID").groupby(["CustomerID","CustomerName"])["UnitPriceINR"].sum().sort_values(ascending=False).head(5)

CustomerID  CustomerName
C226        DJ Apex Kabir    1645000
C202        Simran Kaur      1615000
C243        Rafael Torres    1605000
C259        Bianca Duarte    1570000
C155        Levi Hayes       1500000
Name: UnitPriceINR, dtype: int64

In [42]:
#3
sales_data.merge(products_data, on="ProductID").groupby("ProductName")["Quantity"].count().sort_values(ascending=False).head(3)

ProductName
Titanium Pro X    87
Studio Monarch    86
Reference King    85
Name: Quantity, dtype: int64

In [43]:
#4
c_s_merge = sales_data.merge(customers_data, on="CustomerID")
c_s_merge.assign(
    Revenue = c_s_merge['Quantity'] * c_s_merge['UnitPriceINR']
).groupby("City")['Revenue'].sum().sort_values(ascending=False)

City
Delhi          15535000
Berlin         15480000
New York       15460000
Los Angeles    14995000
Tokyo          14855000
Toronto        14240000
Dubai          13290000
London         13100000
Bangalore      12410000
Singapore      12000000
Amsterdam      11855000
Mumbai          9735000
Seoul           9120000
Paris           7085000
Sydney          6910000
Name: Revenue, dtype: int64

In [44]:
#5
sales_data.groupby("CustomerID").size()

CustomerID
C1      2
C10     1
C100    1
C101    4
C102    3
       ..
C95     3
C96     1
C97     1
C98     4
C99     2
Length: 358, dtype: int64

In [45]:
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1097 entries, 0 to 645
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       1097 non-null   object
 1   OrderDate     1097 non-null   datetime64[ns]
 2   ProductID     1097 non-null   object
 3   CustomerID    1097 non-null   object
 4   Quantity      1097 non-null   int64
 5   UnitPriceINR  1097 non-null   int64
 6   Year          1097 non-null   int32
 7   BigOrder      1097 non-null   object
 8   PriceTier     1097 non-null   object
dtypes: datetime64[ns](1), int32(1), int64(2), object(5)
memory usage: 81.4+ KB

In [46]:
sales_data.describe()

                           OrderDate     Quantity   UnitPriceINR         Year
count                           1097  1097.000000    1097.000000  1097.000000
mean   2025-02-02 04:51:24.776663552     1.103920  187028.258888  2024.588879
min              2024-01-01 00:00:00     1.000000  120000.000000  2024.000000
25%              2024-08-18 00:00:00     1.000000  155000.000000  2024.000000
50%              2025-03-01 00:00:00     1.000000  180000.000000  2025.000000
75%              2025-07-29 00:00:00     1.000000  220000.000000  2025.000000
max              2025-12-28 00:00:00     9.000000  250000.000000  2025.000000
std                              NaN     0.521572   37284.809875     0.492262

In [47]:
sales_data.head(2)

,OrderID,OrderDate,ProductID,CustomerID,Quantity,UnitPriceINR,Year,BigOrder,PriceTier
0,S2024_001,2024-06-22,P3,C12,1,180000,2024,No,Premium
1,S2024_002,2024-11-26,P1,C45,1,120000,2024,No,Standard

In [48]:
products_data.groupby("ProductName")["BasePriceINR"].mean().idxmax()

'Zeus Audio Pro'

In [49]:
products_data.groupby("ProductName")["BasePriceINR"].mean().sort_values(ascending=False).head(1)

ProductName
Zeus Audio Pro    250000.0
Name: BasePriceINR, dtype: float64

In [50]:
products_data.head(2)

,ProductID,ProductName,Category,LaunchYear,BasePriceINR,DriverType,ImpedanceOhm
0,P1,Titan X Elite,Flagship,2023,120000,Tribrid,16
1,P2,Aurora MKII,Flagship,2023,150000,Hybrid,18

In [51]:
products_data['status'] = products_data["BasePriceINR"].apply(lambda price: "Costly" if price > 100000 else "Normal")

In [52]:
products_data

,ProductID,ProductName,Category,LaunchYear,BasePriceINR,DriverType,ImpedanceOhm,status
0,P1,Titan X Elite,Flagship,2023,120000,Tribrid,16,Costly
1,P2,Aurora MKII,Flagship,2023,150000,Hybrid,18,Costly
2,P3,Phantom Ultra,Flagship,2024,180000,Tribrid,12,Costly
3,P4,Sonic Emperor Pro,Flagship,2024,200000,Quadbrid,10,Costly
4,P5,Valkyrie Xtreme,Flagship,2023,170000,Hybrid,14,Costly
5,P6,Obsidian X,Flagship,2024,210000,Tribrid,15,Costly
6,P7,Nebula Prime,Flagship,2023,160000,Hybrid,20,Costly
7,P8,Crimson Audio X,Flagship,2024,230000,Quadbrid,8,Costly
8,P9,Royal Bassline,Flagship,2023,190000,Dynamic,22,Costly
9,P10,Studio Monarch,Flagship,2024,175000,Hybrid,16,Costly
10,P11,Zeus Audio Pro,Flagship,2024,250000,Quadbrid,9,Costly
11,P12,Titanium Pro X,Flagship,2025,220000,Tribrid,13,Costly
12,P13,Harmonic Beast,Flagship,2023,140000,Dynamic,24,Costly
13,P14,Galaxy Monitor,Flagship,2025,155000,Hybrid,18,Costly
14,P15,Reference King,Flagship,2025,240000,Quadbrid,11,Costly

In [53]:
sales_data["status"] = sales_data["UnitPriceINR"].apply(lambda price: "Costly" if price > 200000 else "Normal Price")

In [54]:
sales_data.status.value_counts()

status
Normal Price    708
Costly          389
Name: count, dtype: int64

🥊 Round 7 – Analyst Style Practice
1) High Value Orders: Show all orders where OrderValue > 500000.
2) Unique Products: Find how many unique products were sold in total.
3) Product Revenue Ranking: Rank products based on total revenue.
4) VIP Spending Analysis: Find total spending by each VIPLevel.
5) Harder – Customer Favorite Product: Find the most frequently purchased product for each customer.

In [ ]:
sales_data.assign(
    OrderValue = sales_data["Quantity"] * sales_data["UnitPriceINR"]
)

KeyError: 'OrderValue'

In [ ]:
#2
sales_data.merge(products_data, on="ProductID").groupby("ProductName")["UnitPriceINR"].sum().sort_values(ascending=False).head(1)

ProductName
Reference King    20400000
Name: UnitPriceINR, dtype: int64

In [82]:
#3
sales_data.merge(products_data, on="ProductID").groupby("ProductName")["UnitPriceINR"].sum().rank(ascending=False, method="max").astype("int64").sort_values(ascending=True).head(1)

ProductName
Reference King    1
Name: UnitPriceINR, dtype: int64

In [86]:
#4
s_c_data = sales_data.merge(customers_data, on="CustomerID")
s_c_data.assign(
    Revenue = s_c_data["Quantity"] * s_c_data["UnitPriceINR"] 
).groupby("VIPLevel")["Revenue"].sum().sort_values(ascending=False)

VIPLevel
Bronze      176165000
Gold          4300000
Platinum      2805000
Silver        2800000
Name: Revenue, dtype: int64

In [92]:
#5
sales_data.merge(customers_data, on="CustomerID").groupby("ProductID")["Quantity"].count().sort_values(ascending=False)

ProductID
P12    70
P15    70
P3     70
P10    69
P6     68
P13    62
P11    59
P2     59
P14    59
P4     58
P1     57
P7     55
P5     54
P8     53
P9     50
Name: Quantity, dtype: int64

In [ ]:
# ROUND 8 tommororw