In [1]:
import pandas as pd

In [2]:
customers_data = pd.read_csv("Customers.csv")
products_data = pd.read_csv("Products.csv")
sales_2024 = pd.read_csv("Sales_2024.csv")
sales_2025 = pd.read_csv("Sales_2025.csv")
print("All csv files are saved in the given variables.")

All csv files are saved in the given variables.

In [3]:
customers_data.head(5)

,CustomerID,CustomerName,CustomerType,City,Country,JoinedYear,VIPLevel
0,C1,DJ Arman Blaze,DJ,Mumbai,India,2022,Platinum
1,C2,Sonic Wave Studios,Studio Engineer,Delhi,India,2021,Gold
2,C3,Neon Pulse,Producer,Bangalore,India,2023,Gold
3,C4,Aural Mastering Lab,Studio Engineer,London,UK,2020,Platinum
4,C5,DJ TitanBeats,DJ,Dubai,UAE,2022,Gold

In [4]:
customers_data.shape

(330, 7)

In [5]:
products_data.head(5)

,ProductID,ProductName,Category,LaunchYear,BasePriceINR,DriverType,ImpedanceOhm
0,P1,Titan X Elite,Flagship,2023,120000,Tribrid,16
1,P2,Aurora MKII,Flagship,2023,150000,Hybrid,18
2,P3,Phantom Ultra,Flagship,2024,180000,Tribrid,12
3,P4,Sonic Emperor Pro,Flagship,2024,200000,Quadbrid,10
4,P5,Valkyrie Xtreme,Flagship,2023,170000,Hybrid,14

In [6]:
products_data.shape

(15, 7)

In [7]:
sales_2024.head(5)

     OrderID   OrderDate ProductID CustomerID  Quantity  UnitPriceINR
0  S2024_001  22-06-2024        P3        C12         1        180000
1  S2024_002  26-11-2024        P1        C45         1        120000
2  S2024_003  22-04-2024        P7       C102         1        160000
3  S2024_004  15-05-2024        P4        C88         1        200000
4  S2024_005  04-08-2024        P9       C150         1        190000

In [8]:
sales_2024.shape

(451, 6)

In [9]:
sales_2025.head(5)

     OrderID   OrderDate ProductID CustomerID  Quantity  UnitPriceINR
0  S2025_001  23-08-2025        P3       C206         1        180000
1  S2025_002  26-11-2025        P1       C183         1        120000
2  S2025_003  03-05-2025        P7       C291         1        160000
3  S2025_004  29-05-2025        P4       C207         1        200000
4  S2025_005  23-12-2025        P9       C204         1        190000

In [10]:
sales_2025.shape

(646, 6)

🥊 Round 1 – Data Analysis Tasks
1) I want to know how many total orders were placed in 2024 and 2025 combined, Return one number only.
2) Show me top 5 customers who purchased the most quantity of products across both years combined.
- Output should contain:
- CustomerID
- TotalQuantity

3) I want to understand which product generated the highest revenue across both years.
- Revenue = Quantity * UnitPriceINR

In [11]:
customers_data['VIPLevel'] = customers_data['VIPLevel'].str.replace('0', 'Bronze')

In [12]:
customers_data.VIPLevel.value_counts()

VIPLevel
Bronze      300
Gold         15
Platinum      9
Silver        6
Name: count, dtype: int64

In [13]:
# Q.2
sales_data = pd.concat([sales_2024, sales_2025])

In [14]:
sales_n_customers = sales_data.merge(customers_data, on = "CustomerID").merge(products_data, on = "ProductID")

sales_n_customers.groupby('CustomerID')['Quantity'].sum().sort_values(ascending=False).head(5)

CustomerID
C330    11
C226    10
C202    10
C266     9
C232     9
Name: Quantity, dtype: int64

In [15]:
products_data.head(2)

,ProductID,ProductName,Category,LaunchYear,BasePriceINR,DriverType,ImpedanceOhm
0,P1,Titan X Elite,Flagship,2023,120000,Tribrid,16
1,P2,Aurora MKII,Flagship,2023,150000,Hybrid,18

In [16]:
sales_data.merge(products_data, on="ProductID").groupby("ProductName")[["Quantity", "UnitPriceINR"]].sum().sort_values(by="UnitPriceINR", ascending=False)

                   Quantity  UnitPriceINR
ProductName
Reference King           89      20400000
Titanium Pro X           90      19140000
Zeus Audio Pro           88      18500000
Obsidian X               87      17640000
Studio Monarch           96      15050000
Phantom Ultra            81      14220000
Crimson Audio X          66      13570000
Sonic Emperor Pro        76      13200000
Valkyrie Xtreme          75      11730000
Royal Bassline           64      11400000
Galaxy Monitor           84      10850000
Harmonic Beast           80      10360000
Aurora MKII              84      10350000
Nebula Prime             72      10240000
Titan X Elite            79       8520000

In [17]:
sales_data.head(2)

     OrderID   OrderDate ProductID CustomerID  Quantity  UnitPriceINR
0  S2024_001  22-06-2024        P3        C12         1        180000
1  S2024_002  26-11-2024        P1        C45         1        120000

In [18]:
sales_data['OrderDate'] = pd.to_datetime(sales_data['OrderDate'])

C:\Users\Kartik\AppData\Local\Temp\ipykernel_26616\3540728264.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  sales_data['OrderDate'] = pd.to_datetime(sales_data['OrderDate'])

In [19]:
sales_data['Year'] = sales_data['OrderDate'].dt.year

In [20]:
sales_data['OrderID'].count()

len(sales_data)

1097

In [21]:
sales_data

       OrderID  OrderDate ProductID CustomerID  Quantity  UnitPriceINR  Year
0    S2024_001 2024-06-22        P3        C12         1        180000  2024
1    S2024_002 2024-11-26        P1        C45         1        120000  2024
2    S2024_003 2024-04-22        P7       C102         1        160000  2024
3    S2024_004 2024-05-15        P4        C88         1        200000  2024
4    S2024_005 2024-08-04        P9       C150         1        190000  2024
..         ...        ...       ...        ...       ...           ...   ...
641  S2025_642 2025-02-22       P15       C282         1        240000  2025
642  S2025_643 2025-04-02       P10       C344         1        175000  2025
643  S2025_644 2025-04-17       P13       C150         1        140000  2025
644  S2025_645 2025-05-04        P2       C240         1        150000  2025
645  S2025_646 2025-12-07        P4       C239         1        200000  2025

[1097 rows x 7 columns]

In [22]:
sales_data

       OrderID  OrderDate ProductID CustomerID  Quantity  UnitPriceINR  Year
0    S2024_001 2024-06-22        P3        C12         1        180000  2024
1    S2024_002 2024-11-26        P1        C45         1        120000  2024
2    S2024_003 2024-04-22        P7       C102         1        160000  2024
3    S2024_004 2024-05-15        P4        C88         1        200000  2024
4    S2024_005 2024-08-04        P9       C150         1        190000  2024
..         ...        ...       ...        ...       ...           ...   ...
641  S2025_642 2025-02-22       P15       C282         1        240000  2025
642  S2025_643 2025-04-02       P10       C344         1        175000  2025
643  S2025_644 2025-04-17       P13       C150         1        140000  2025
644  S2025_645 2025-05-04        P2       C240         1        150000  2025
645  S2025_646 2025-12-07        P4       C239         1        200000  2025

[1097 rows x 7 columns]

In [23]:
sales_data.assign(
    Revenue = sales_data['Quantity'] * sales_data['UnitPriceINR']
).groupby("ProductID")['Revenue'].sum().sort_values(ascending=False)

ProductID
P11    22000000
P15    21360000
P12    19800000
P6     18270000
P10    16800000
P4     15200000
P8     15180000
P3     14580000
P14    13020000
P5     12750000
P2     12600000
P9     12160000
P7     11520000
P13    11200000
P1      9480000
Name: Revenue, dtype: int64

🥊 Round 2 – New Tasks (No Hints)
1) Show me total revenue generated in 2024 and 2025 separately. OUTPUT: Year | TotalRevenue

2) Find top 3 cities that purchased the highest number of products. OUTPUT: City | TotalQuantity

3) I want to know which DriverType generated the highest revenue. OUTPUT: DriverType | TotalRevenue

In [24]:
# Q.1
sales_data.assign(
    Revenue = sales_data["Quantity"] * sales_data["UnitPriceINR"]
).groupby("Year")["Revenue"].sum()

Year
2024     92630000
2025    133290000
Name: Revenue, dtype: int64

In [25]:
# Q.2
sales_data.merge(products_data, on="ProductID").merge(customers_data, on="CustomerID").groupby("City")['Quantity'].sum().sort_values(ascending=False).head(3)

City
Delhi          83
Los Angeles    81
Berlin         81
Name: Quantity, dtype: int64

In [26]:
#Q. 3
mereged_data = sales_data.merge(products_data, on="ProductID")
mereged_data.assign(
    Revenue = mereged_data["Quantity"] * mereged_data['UnitPriceINR']
).groupby("DriverType")["Revenue"].sum().sort_values(ascending=False).head(1)

DriverType
Quadbrid    73740000
Name: Revenue, dtype: int64

🥊 Round 3 – New Boss Requests

1) I want to know which 5 products generated the highest total revenue across both years.  ProductName | TotalRevenue

2) Find how many customers belong to each VIP level.  VIPLevel | CustomerCount

3) I want to know which customer spent the most money across both years. OUTPUT: CustomerName | TotalSpent

In [27]:
# Q.1
mereged_data.assign(
    Revenue = mereged_data["Quantity"] * mereged_data['UnitPriceINR']
).groupby("ProductName")['Revenue'].sum().sort_values(ascending=False).head(5)

ProductName
Zeus Audio Pro    22000000
Reference King    21360000
Titanium Pro X    19800000
Obsidian X        18270000
Studio Monarch    16800000
Name: Revenue, dtype: int64

In [28]:
# Q.2
customers_data['VIPLevel'].value_counts()

VIPLevel
Bronze      300
Gold         15
Platinum      9
Silver        6
Name: count, dtype: int64

In [29]:
# Q.3
merge_cs = sales_data.merge(customers_data, on="CustomerID")
merge_cs.assign(
    Revenue = merge_cs["Quantity"] * merge_cs['UnitPriceINR']
).groupby("CustomerName")["Revenue"].sum().sort_values(ascending=False).head(1)

CustomerName
DJ Apex Kabir    2035000
Name: Revenue, dtype: int64

🥊 Round 4 — Boss Needs New Analysis 
1) Find top 5 countries that generated the highest revenue.   Country | TotalRevenue
2) I want to know which year sold the highest number of products (by quantity).   Year | TotalQuantity
3) Find the most popular product category based on total quantity sold.  Category | TotalQuantity

In [30]:
#1
cus_and_sales_merge = sales_data.merge(customers_data, on="CustomerID")
cus_and_sales_merge.assign(
    Revenue = cus_and_sales_merge["Quantity"] * cus_and_sales_merge["UnitPriceINR"]
).groupby("Country")["Revenue"].sum().sort_values(ascending=False).head(5)

Country
India            37680000
United States    29705000
Germany          15480000
Japan            14855000
Canada           14240000
Name: Revenue, dtype: int64

In [31]:
#2
sales_data.groupby("Year")["Quantity"].sum().sort_values(ascending=False).head(1)

Year
2025    714
Name: Quantity, dtype: int64

In [32]:
#3
sales_data.merge(products_data, on="ProductID").groupby("Category")["Quantity"].sum().sort_values(ascending=False).head(1)

Category
Flagship    1211
Name: Quantity, dtype: int64

🥊 Round 5 – Mixed Pandas Practice
1) Show all sales where Quantity > 3.
- OrderID
- ProductID
- Quantity
- UnitPriceINR

2) Create a new column called: BigOrder
- Quantity >= 3 → "Yes"
- otherwise → "No"

3) Find the average price of products in each Category.
- Category | AvgPrice          Sorted highest first.

4) Show all Platinum customers from India.
- CustomerName
- City
- Country
- VIPLevel

5) Harder – Order Value: Create a column: OrderValue = Quantity * UnitPriceINR Then find top 5 highest single orders.
- OrderID
- CustomerID
- OrderValue

In [33]:
#1
sales_data[sales_data['Quantity'] > 3] [["OrderID","ProductID","Quantity","UnitPriceINR"]]

       OrderID ProductID  Quantity  UnitPriceINR
111  S2024_112        P8         4        230000
171  S2024_172       P14         6        155000
327  S2024_328        P1         4        120000
337  S2024_338       P11         4        250000
357  S2024_358        P5         4        170000
446  S2024_447       P13         4        140000
111  S2025_112        P8         4        230000
171  S2025_172       P14         6        155000
327  S2025_328        P1         4        120000
337  S2025_338       P11         4        250000
357  S2025_358        P5         4        170000
446  S2025_447       P13         4        140000
534  S2025_535        P6         4        210000
640  S2025_641       P10         9        175000

In [34]:
import numpy as np

sales_data["BigOrder"] = np.where(sales_data['Quantity'] >= 3, "Yes", "No")

In [35]:
sales_data[sales_data['BigOrder'] == "Yes"].head(2)

,OrderID,OrderDate,ProductID,CustomerID,Quantity,UnitPriceINR,Year,BigOrder
91,S2024_092,2024-02-28,P4,C19,3,200000,2024,Yes
111,S2024_112,2024-02-25,P8,C163,4,230000,2024,Yes

In [36]:
#3
products_data.groupby("Category")['BasePriceINR'].mean().sort_values(ascending=False)

Category
Flagship    186000.0
Name: BasePriceINR, dtype: float64

In [37]:
#4
customers_data[customers_data['VIPLevel'] == "Platinum"] [["CustomerName","City","Country","VIPLevel"]]

              CustomerName         City  Country  VIPLevel
0           DJ Arman Blaze       Mumbai    India  Platinum
3      Aural Mastering Lab       London       UK  Platinum
5         Studio Harmonics  Los Angeles      USA  Platinum
8       Platinum Sound Lab       Berlin  Germany  Platinum
11     Crystal Mix Studios       London       UK  Platinum
15        Velvet Audio Lab  Los Angeles      USA  Platinum
21  Harmonic Fusion Studio     New York      USA  Platinum
24    Golden Frequency Lab  Los Angeles      USA  Platinum
27     SonicAlchemy Studio       London       UK  Platinum

In [38]:
#5
sales_data.assign(
    OrderValue = sales_data['Quantity'] * sales_data["UnitPriceINR"]
).sort_values(by="OrderValue", ascending=False) [["OrderID","CustomerID","OrderValue"]]

       OrderID CustomerID  OrderValue
640  S2025_641       C385     1575000
337  S2025_338       C384     1000000
337  S2024_338       C267     1000000
171  S2025_172       C332      930000
171  S2024_172        C44      930000
..         ...        ...         ...
79   S2024_080       C269      120000
325  S2025_326       C319      120000
321  S2025_322       C394      120000
206  S2024_207        C83      120000
184  S2024_185       C210      120000

[1097 rows x 3 columns]